package teampixl.com.pixlpos.database.api;

public enum StatusCode {
    SUCCESS,
    FAILURE,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_UPDATE_FAILED,
    INVALID_USER_ID,
    INVALID_USERNAME,
    INVALID_EMAIL,
    INVALID_FIRST_NAME,
    INVALID_LAST_NAME,
    INVALID_PASSWORD,
    INVALID_USER_ROLE,
    INVALID_USER_STATUS,
    INVALID_USER_ADDITIONAL_INFO,
}