name: Rollback on Failure

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint", "Build", "Run Unit Tests"]
    types:
      - completed

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Last Successful Commit for Branch
        id: find_commit
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          last_good_commit=$(git log --tags="deployed_${branch_name}_*" --format=format:"%H" -n 1)
          if [ -z "$last_good_commit" ]; then
            echo "No previous successful commit found."
            exit 1
          fi
          echo "Last good commit for branch: $last_good_commit"
          echo "last_good_commit=$last_good_commit" >> $GITHUB_ENV

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Revert to Last Successful Commit (excluding workflow files)
        run: |
          git reset --hard ${{ env.last_good_commit }}
          git reset --soft HEAD@{1}  # Keep the reset commit but make changes unstaged
          git restore --staged .github/workflows/  # Exclude workflow files from the commit
          git commit -m "Revert to last successful commit without changing workflows"
          git push --force
