name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      success: ${{ steps.build.outcome == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        id: build
        run: mvn clean install
