name: Compendium

on:
  push:
    branches:
      - 'development'
      - 'quality'
      - 'production'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [lint, build, test]
    if: ${{ needs.lint.outputs.success && needs.build.outputs.success && needs.test.outputs.success }}
    uses: ./.github/workflows/deploy.yml

  rollback:
    needs: [lint, build, test]
    if: ${{ !needs.lint.outputs.success || !needs.build.outputs.success || !needs.test.outputs.success }}
    uses: ./.github/workflows/rollback.yml
