name: Compendium

on:
  push:
    branches:
      - 'development'
      - 'quality'
      - 'production'
  pull_request:
    branches:
      - 'development'
      - 'quality'
      - 'production'

jobs:
  Compendium:
    uses: parkermmr/compendium/.github/workflows/compendium-java.yml@main
    with: 
      java-version: "21"
      distribution: "corretto"
      ref-name: ${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
