name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tag Successful Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "deployed_{{ github.ref_name }}_{{ github.sha }}" -m "Deployment tag for {{ github.sha }}"
          git push origin "deployed_{{ github.ref_name }}_{{ github.sha }}"


