name: Java Linter

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    outputs:
      success: ${{ steps.parse_checkstyle.outcome == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Checkstyle
        run: |
          curl -LJO "https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar"
          mv checkstyle-10.12.0-all.jar /usr/local/bin/checkstyle.jar

      - name: Run Checkstyle
        run: |
          java -jar /usr/local/bin/checkstyle.jar -c /google_checks.xml src/ > checkstyle-result.txt

      - name: Parse Checkstyle output for warnings and errors
        id: parse_checkstyle
        run: |
          errors=$(grep -c "error" checkstyle-result.txt)
          echo "Errors: $errors"
          if [ "$errors" -gt 0 ]; then
            exit 1
          fi

