name: Java Linter

on:
  push:
    branches:
      - 'development'
      - 'quality'
      - 'production'
  pull_request:
    branches:
      - 'development'
      - 'quality'
      - 'production'

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Checkstyle
        run: |
          curl -LJO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar
          mv checkstyle-10.12.0-all.jar /usr/local/bin/checkstyle.jar

      - name: Run Checkstyle and save output
        run: |
          java -jar /usr/local/bin/checkstyle.jar -c /google_checks.xml src/ > checkstyle-result.txt || true
        continue-on-error: true

      - name: Parse Checkstyle output for warnings and errors
        id: parse_checkstyle
        run: |
          errors=$(grep -o -E "error" checkstyle-result.txt | wc -l)
          warnings=$(grep -o -E "warning|WARN" checkstyle-result.txt | wc -l)
          echo "Warnings: $warnings"
          echo "Errors: $errors"
          echo "::set-output name=warnings::$warnings"
          echo "::set-output name=errors::$errors"

      - name: Fail if too many warnings or any errors
        run: |
          if [ ${{ steps.parse_checkstyle.outputs.errors }} -gt 0 ] || [ ${{ steps.parse_checkstyle.outputs.warnings }} -gt 10 ]; then
            echo "Too many warnings or errors found. Failing the job."
            exit 1
          fi
