name: Java Linter

on:
  workflow_call:
    outputs:
      success:
        description: 'Whether the lint job succeeded.'
        value: ${{ jobs.lint.outputs.success }}

jobs:
  lint:
    runs-on: ubuntu-latest

    outputs:
      success: ${{ job.status == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Checkstyle
        run: |
          curl -LJO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar
          mv checkstyle-10.12.0-all.jar /usr/local/bin/checkstyle.jar

      - name: Run Checkstyle and save output
        run: |
          java -jar /usr/local/bin/checkstyle.jar -c google src/ > checkstyle-result.txt 2>&1
        continue-on-error: true

      - name: Parse Checkstyle output for warnings and errors
        id: parse_checkstyle
        run: |
          errors=$(grep -c '^\[ERROR\]' checkstyle-result.txt)
          warnings=$(grep -c '^\[WARN\]' checkstyle-result.txt)
          echo "Warnings: $warnings"
          echo "Errors: $errors"
          echo "errors=$errors" >> $GITHUB_ENV

      - name: Display Checkstyle Errors
        if: env.errors != '0'
        run: |
          echo "### Checkstyle Errors:"
          grep '^\[ERROR\]' checkstyle-result.txt || echo "No errors found."

      - name: Fail if any errors
        run: |
          if [ ${{ env.errors }} -gt 0 ]; then
            echo "Errors found. Failing the job."
            exit 1
          fi
