name: Build and Package JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21 with Amazon Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Download and Setup JavaFX
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.4/openjfx-21.0.4_linux-x64_bin-sdk.zip -O javafx-sdk.zip
          unzip javafx-sdk.zip -d /opt
          echo "JAVA_FX_HOME=/opt/javafx-sdk-21.0.4" >> $GITHUB_ENV
          echo "$JAVA_FX_HOME/lib" >> $GITHUB_PATH

      - name: Build with Maven and Shade Plugin
        run: |
          mvn clean package

      - name: Verify JAR creation
        run: |
          ls -l target/

      - name: Create Dynamic Tag
        id: create_tag
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "TAG_NAME=release-${BRANCH_NAME}-${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Create Release with Dynamic Tag
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.TAG_NAME }} target/PIXL-POS-1.0.jar --title "Release ${{ env.TAG_NAME }}" --notes "Automated release of PIXL-POS JAR"

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/PIXL-POS-1.0.jar
          asset_name: PIXL-POS-1.0.jar
          asset_content_type: application/java-archive

  build-windows:
    needs: build-linux
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21 with Amazon Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Download and Setup JavaFX
        run: |
          curl -L "https://download2.gluonhq.com/openjfx/21.0.4/openjfx-21.0.4_windows-x64_bin-sdk.zip" -o javafx-sdk.zip
          Expand-Archive javafx-sdk.zip -DestinationPath C:\javafx-sdk
          echo "JAVA_FX_HOME=C:\javafx-sdk" | Out-File -Append -Encoding ASCII $env:GITHUB_ENV

      - name: Build with Maven and Shade Plugin
        run: mvn clean package

      - name: Verify JAR creation (Windows)
        run: |
          dir target

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/PIXL-POS-1.0.jar
          asset_name: PIXL-POS-1.0.jar
          asset_content_type: application/java-archive
