name: Rollback on Failure

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Last Successful Commit for Branch
        id: find_commit
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          last_good_commit=$(git log --tags="deployed_${branch_name}_*" --format=format:"%H" -n 1)
          if [ -z "$last_good_commit" ]; then
            echo "No previous successful commit found."
            exit 1
          fi
          echo "Last good commit for branch: $last_good_commit"
          echo "last_good_commit=$last_good_commit" >> $GITHUB_ENV

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Rollback Commit Without Workflow Files
        run: |
          git checkout ${{ env.last_good_commit }} -- . ':!**/.github/workflows/*'
          git checkout -b temp-rollback-branch
          git commit -m "Rollback to commit ${{ env.last_good_commit }} excluding workflow files"
          git push origin temp-rollback-branch:development --force

      - name: Clean up Temporary Branch
        run: |
          git branch -D temp-rollback-branch
