name: Rollback on Failure

on:
  workflow_call:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Find Last Successful Commit
        run: |
          last_good_commit=$(git rev-list --tags='deployed_*' --max-count=1)
          if [ -z "$last_good_commit" ]; then
            echo "No previous successful deployment found."
            exit 1
          fi

      - name: Revert to Last Successful Commit (excluding workflow files)
        run: |
          git reset --hard ${{ env.last_good_commit }}
          git reset --soft HEAD@{1}  # Keep the reset commit but make changes unstaged
          git restore --staged .github/workflows/  # Exclude workflow files from the commit
          git commit -m "Revert to last successful commit without changing workflows"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force
