name: Rollback on Failure

on:
  push:
    branches:
      - "development"
  workflow_run:
    workflows: ["Java Linter"]
    types:
      - completed

jobs:
  rollback:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Last Successful Commit
        id: find_commit
        run: |
          last_good_commit=$(git log --grep="Pipeline passed" -n 1 --format=format:"%H")
          echo "last_good_commit=$last_good_commit" >> $GITHUB_ENV

      - name: Revert to Last Successful Commit
        run: |
          git reset --hard ${{ env.last_good_commit }}
          git push --force
