name: Rollback on Failure

on:
  workflow_run:
    workflows: ["Java Linter"]
    types:
      - completed

  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Last Successful Commit
        id: find_commit
        run: |
          last_good_commit=$(git log --tags='pipeline_passed_*' --format=format:"%H" -n 1)
          echo "Last good commit: $last_good_commit"
          echo "last_good_commit=$last_good_commit" >> $GITHUB_ENV

      - name: Revert to Last Successful Commit
        run: |
          git reset --hard ${{ env.last_good_commit }}
          git push --force
