name: Rollback on Failure

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Last Successful Commit for Branch
        id: find_commit
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          last_good_commit=$(git log --tags="deployed_${branch_name}_*" --format=format:"%H" -n 1)
          if [ -z "$last_good_commit" ]; then
            echo "No previous successful commit found."
            exit 1
          fi
          echo "Last good commit for branch: $last_good_commit"
          echo "last_good_commit=$last_good_commit" >> $GITHUB_ENV

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Revert to Last Successful Commit
        run: |
          git reset --hard ${{ env.last_good_commit }}
          git reset HEAD .github/workflows/  # Unstage changes in the workflows directory

      - name: Check for Changes to Commit
        id: check_changes
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit."
            echo "skip_commit=true" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "skip_commit=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Reversion (if changes)
        if: env.skip_commit == 'false'
        run: |
          git commit -m "Reverted to last successful commit without changing workflows"
          git push --force  # Force push to ensure the rollback is reflected in the remote branch

      - name: Force Push Reset (No Changes Detected)
        if: env.skip_commit == 'true'
        run: |
          git push --force  # Force push even if there are no changes to commit, to update the branch to the reset commit
