name: Run Unit Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    outputs:
      success: ${{ steps.junit.outcome == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and run tests
        id: junit
        run: mvn test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports
