name: Unit Tests

on:
  push:
    branches:
      - 'development'
      - 'quality'
      - 'production'
  pull_request:
    branches:
      - 'development'
      - 'quality'
      - 'production'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: |
          mvn test

      - name: Check Java Version
        run: java -version

      - name: List Test Source Files
        run: ls -R src/test/java/

      - name: List Compiled Test Classes
        run: ls -R target/test-classes/

      - name: Clean Build
        run: mvn clean

      - name: Force Recompile
        run: mvn clean compile test-compile test

      - name: Run Unit Tests
        run: |
          mvn test

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Manual Test Execution
        run: |
          find target/test-classes -name '*Test.class' -exec java org.junit.platform.console.ConsoleLauncher -cp target/classes:target/test-classes -c {} \;
